language: ruby
rvm:
  - 2.4.1
env:
  - RAILS_ENV=test
  - NODE_ENV=test
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
install:
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
  - bundle install
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database travis_test_db;' -U postgres
  - cp ./config/database.travis.yml ./config/database.yml
  - bundle exec sidekiq -d -L /tmp/sidekiq.log
  - sleep 3
  - ./bin/rake webpacker:compile
  - sleep 3
services:
  - redis-server
script:
  - bundle exec rails db:schema:load
  - bundle exec rails db:test:prepare
  - bundle exec rails test
after_failure:
  - cat ./config/database.yml
  - echo $RAILS_ENV
  - bundle exec rake --version
